dist: trusty
notifications:
  email: false
fail_fast: true
language: go
go:
- 1.x
sudo: false
os:
- linux
addons:
  postgresql: '9.5'
install:
- go get -u github.com/golang/lint/golint
- go get github.com/gobuffalo/pop/...
- go install github.com/gobuffalo/pop/soda
before_script:
- psql -c 'create database feedsys;' -U postgres
- psql -c "CREATE USER bigbang WITH PASSWORD 'bigbang';" -U postgres
- psql -c "ALTER USER bigbang WITH SUPERUSER;" -U postgres
before_install:
- V=0.20.0
- OS=linux
- URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
- wget -O install.sh "${URL}"
- chmod +x install.sh
- "./install.sh --user"
- rm -f install.sh
script:
- bazel clean
- bazel run //:gazelle
- soda reset -e development
- bazel test --config=ci  //test/integration/...
