#!/usr/bin/env bash
bazel clean
bazel run //:gazelle
./run_unit_test.sh  //cmd/lambda/feed/feed_events_table_creator/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/profile/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/get_profile/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/feed_post/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/get_feed_post/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/get_batch_posts/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/get_recent_posts/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/attach_session/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/get_session/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/refuel/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/dev_refuel/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/feed_update_post_rewards/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/feed_upvote/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/get_recent_votes/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/deactivate_actor/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/feed_token_generator/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed/reset_actor_fuel/config:go_default_test
