#!/usr/bin/env bash
bazel clean
bazel run //:gazelle
./run_unit_test.sh  //cmd/lambda/feed_events_table_creator/config:go_default_test
./run_unit_test.sh  //cmd/lambda/profile/config:go_default_test
./run_unit_test.sh  //cmd/lambda/get_profile/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed_post/config:go_default_test
./run_unit_test.sh  //cmd/lambda/get_feed_post/config:go_default_test
./run_unit_test.sh  //cmd/lambda/get_batch_posts/config:go_default_test
./run_unit_test.sh  //cmd/lambda/get_recent_posts/config:go_default_test
./run_unit_test.sh  //cmd/lambda/attach_session/config:go_default_test
./run_unit_test.sh  //cmd/lambda/get_session/config:go_default_test
./run_unit_test.sh  //cmd/lambda/refuel/config:go_default_test
./run_unit_test.sh  //cmd/lambda/dev_refuel/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed_update_post_rewards/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed_upvote/config:go_default_test
./run_unit_test.sh  //cmd/lambda/get_recent_votes/config:go_default_test
./run_unit_test.sh  //cmd/lambda/deactivate_actor/config:go_default_test
./run_unit_test.sh  //cmd/lambda/feed_token_generator/config:go_default_test
